RAILS-1 - Создать Dockerfile и docker-compose.yml
sidorovpavel564/rails_user_links pull request #1
Opened 2024-03-25 13:00 UTC by sidorovpavel564

2024-03-25 13:17 UTC, squaretus requested changes

2024-03-25 13:17 UTC, squaretus commented on Dockerfile
> +RUN gem install rails
зачем? у тебя есть Gemfile где и прописан rails нужной версии
а установка его осуществится командой bundle install

2024-03-25 13:17 UTC, squaretus commented on docker-compose.yml
> +        bundle install;
должно быть в файле Dockerfile а не тут

2024-03-25 13:17 UTC, squaretus commented on docker-compose.yml
> +        rake db:create;
должно быть в файле docker-entrypoint.sh а не тут
такое решение подходит для твоего маленького проекта, для рабочей среды у нас отдельный docker-entrypoint-development.sh в котором выполняются миграции, потому что в продакшен среде создание базы выполняется 1 раз всегда, а потом только миграции, и то у нас все автоматизированно и все делает Jenkins

2024-03-25 13:17 UTC, squaretus commented on docker-compose.yml
> +        rake db:migrate;
тоже самое, при каждом запуске будешь базу создавать и миграции проводить
ну и олжно быть в отдельном файле

2024-03-25 13:17 UTC, squaretus commented on docker-compose.yml
> +        rails s -b 0.0.0.0;
для твоего проекта все норм, но у нас потом посмотришь как все работает, у нас в обычно докер файле sleep infinity прописан

2024-03-25 13:17 UTC, squaretus commented on docker-compose.yml
> +    entrypoint: /bin/bash
ненене, такого быть не должно

2024-03-25 13:47 UTC, sidorovpavel564 commented on Dockerfile
> +RUN gem install rails
исправил

2024-03-25 13:47 UTC, sidorovpavel564 commented on docker-compose.yml
> +        bundle install;
исправил

2024-03-25 13:47 UTC, sidorovpavel564 commented on docker-compose.yml
> +        rake db:migrate;
вынес в docker-entrypoint.sh

2024-03-25 13:47 UTC, sidorovpavel564 commented on docker-compose.yml
> +        rails s -b 0.0.0.0;
вынес в docker-entrypoint.sh

2024-03-25 13:47 UTC, sidorovpavel564 commented on docker-compose.yml
> +    entrypoint: /bin/bash
исправил

2024-03-26 07:50 UTC, squaretus commented on docker-compose.yml
> +        rails s -b 0.0.0.0;
не верно вынес
команда запуска сервера должна была остаться тут

2024-03-26 07:50 UTC, squaretus commented on docker-compose.yml
> +    entrypoint: ["/bin/sh", "./docker-entrypoint.sh"]
вот это вообще не нужно
у тебя же стоит .:/app:cached

2024-03-26 07:51 UTC, squaretus requested changes

2024-03-26 07:51 UTC, squaretus commented on docker-entrypoint.sh
> +rails s -b 0.0.0.0
должно быть в command контейнера, я ж написал

2024-03-26 07:51 UTC, squaretus commented on docker-compose.yml
> +    entrypoint: ["/bin/sh", "./docker-entrypoint.sh"]
вот это вообще не нужно
у тебя же стоит .:/app:cached

2024-03-26 07:52 UTC, squaretus commented on docker-compose.yml
> +    entrypoint: /bin/bash
получается исправил не верно
Докер обязательно нужно выучить
это прям первостепенная задача

2024-03-26 07:56 UTC, squaretus commented on docker-compose.yml
> +    entrypoint: ["/bin/sh", "./docker-entrypoint.sh"]
просто 
```
entrypoint: sh ./docker-entrypoint.sh
```

2024-03-26 09:46 UTC, sidorovpavel564 commented on docker-compose.yml
> +        rails s -b 0.0.0.0;
вернул rails s -b 0.0.0.0 обратно в docker-compose

2024-03-26 09:47 UTC, sidorovpavel564 commented on docker-entrypoint.sh
> +rails s -b 0.0.0.0
исправил

2024-03-26 09:47 UTC, sidorovpavel564 commented on docker-compose.yml
> +    entrypoint: ["/bin/sh", "./docker-entrypoint.sh"]
сделал просто `entrypoint: docker-entrypoint.sh`

2024-03-26 10:05 UTC, squaretus approved these changes

2024-03-26 10:30 UTC, merged